name: example
description: Example of usage presentation tools

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=3.7.10"

dependencies:
  flutter:
    sdk: flutter

  presentation:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true