on: [ push, pull_request ]
name: Analyze and Test
jobs:
  build:
    name: Analyze and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ "beta" ]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}
      - run: flutter pub get
      - run: flutter analyze
